### ISSUE TITLE
[Meta issue] List of `cpt.py` improvements

### ISSUE THREAD

**Issue by reikdas** [root-project/cling#406]
- [ ] Use a `if __name__ == "__main__"` block as program execution starting point in `cpt.py`
- [ ] No mutating global variables in `cpt.py`
- [ ] Minimize use of `subprocess` in `cpt.py`
- [ ] Making `cpt.py` `flake8` compliant (with appropriate error/violation codes)
- [ ] Fix `.deb` packaging (existing effort: https://github.com/vgvassilev/cling/pull/214) [#307]
- [ ] Fix `--verbose` flag not printing verbose output in CMake build log (using `cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON` instead of `make VERBOSE=1` might fix this)
- [ ] Do not allow users to use currently "known" broken/untested features in `cpt.py`; comment out relevant parts
- [ ] Revamp argument parser
  - `cpt.py` is both a Cling installer and a packager. It should be possible to build Cling without packaging it.
  - Enable dependent arguments. Ideally, we should be able to pass some arguments only if some other argument is also passed (for eg. it doesn't make sense to pass `--with-llvm-url` if LLVM is being installed from system package manager).
  - Fix nomenclature (we have arguments named `--with-llvm-tar` and `--with-binary-llvm`; there should be some uniformity)
- [ ] Fix builds using LLVM pre-built binary tarballs (on Linux and macOS) and add it to CI
- [ ] Fix builds using LLVM installed from system package manager (on Linux and macOS) and add it to CI
- [ ] Enable builds using LLVM pre-built binaries on Windows and add it to CI
- [ ] Update `cpt.py` README, both in root directory as well as in `tools/packaging` [#372]
- [ ] Use homebrew as default package manager on macOS, instead of macports [#404]
- [ ] Check if installed dependencies are always detected by `--check-requirements` (even if installed by different package manager); also verify list of required dependencies [#404]
- [ ] New flag to specify number of cores to build Cling with [#391]

(Please check off closed issues and add new improvements by editing this top post)
