### ISSUE TITLE
[Meta issue] List of CI and CD improvements

### ISSUE THREAD

**Issue by reikdas** [root-project/cling#407]
- [ ] Add GitHub Actions CI instance that runs `clang-tidy` on PR/commit diff
- [ ] Add GitHub Actions CI instance that runs `clang-format` on PR/commit diff
- [ ] Add GitHub Actions CI instance that runs `codecov` on PR/commit
- [ ] GitHub Actions CD to automatically upload Linux/macOS nightly binaries (we can drop `.travis.yml` after this) [#403]
- [ ] GitHub Actions CD to automatically upload new Linux/macOS release binaries (based on commit tag)
- [ ] Add the [macOS 11.0 runner](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md) to Cling's GitHub Actions CI [#405]
- [ ] Add Windows builds to GitHub Actions CI (existing effort: https://github.com/root-project/root/pull/6750); we can drop `.appveyor.yml` after this [#303]
- [ ] GitHub Actions CD to automatically upload Windows nightly binaries [#337]
- [ ] GitHub Actions CD to automatically upload new Windows release binaries (based on commit tag) [#337]
- [ ] Enable incremental builds in GitHub Actions CI
- [ ] Validate packaged binaries
- [ ] Add GPU CI runner [#386]

(Please check off closed issues and add new improvements by editing this top post)
